name: CI/CD Docker na VM com Chave SSH

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          
      - name: Cache de Dependências Node.js
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Instalar Dependências (Com Cache)
        run: npm install
        
      - name: Executar Testes Unitários com npm test
        run: npm test
        
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build e Push da Imagem Docker (com tag latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERUSERNAME }}/stockapi:latest 

  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    needs: build-test

    steps:
      - name: Deploy na VM via SSH (com Chave SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          key: ${{ secrets.SSHPRIVATEKEY }}
          script: |
            echo "Conectado na VM e atualizando..."
            LATEST_TAG="${{ secrets.DOCKERUSERNAME }}/stockapi:latest"
            
            cd stockapi 

            sed -i "s|image: ${{ secrets.DOCKERUSERNAME }}/stockapi:.*|image: $LATEST_TAG|g" docker-compose.yml
            
            docker-compose down
            docker-compose pull app 
            docker-compose up -d 
            
            echo "Deploy concluído com sucesso com a tag latest"
            
            docker image prune -f