name: CI/CD Docker na VM com Chave SSH

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build e Push da Imagem Docker (com tag latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERUSERNAME }}/stockapi:latest 

      - name: Deploy na VM via SSH (com Chave)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          key: ${{ secrets.SSHPRIVATE_KEY }}
          script: |
            echo "Conectado na VM e atualizando..."
            LATEST_TAG="${{ secrets.DOCKERUSERNAME }}/stockapi:latest"
            
            cd stockapi 

            sed -i "s|image: ${{ secrets.DOCKERUSERNAME }}/stockapi:.*|image: $LATEST_TAG|g" docker-compose.yml
            
            docker-compose down
            
            docker-compose pull app 
            
            docker-compose up -d 
            
            echo "Deploy concluído com sucesso com a tag latest"
            
            docker image prune -f